language: java

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache


addons:
  apt:
    packages:
    - jq
  sonarcloud:
    organization: "ian4hu-github" # the key of the org you chose at step #3
    token:
      secure: "Fnm6UByZ8XM06X3D278wgduusOlFHRqu/zDe0sre9+ynOD22K8WJsDkE2ZHmcuSaGOZOQbhlsT0czi0JqblQrjXw9pnLs23QMWxcQxrkiWpm8Ko6nFER1Lcf0Nx+S1IFdEe/9iK7z0Afppj3BlhZcvnobgg4jkU54Ut6JaEl86S7hEsEBt79LinEfpb72gNCXTCtHxnH+bL+p+Dvs1aal7GLTwojV8j4BPkqzsxStQpSi6pe58HRapxxcxYpErpKYdFY+XBJfoc7Wr+a1X6xpwZAI0AmgcQTlpyfhv9/DpPxejkx+baBQHgl5xNIs7qpQjw+Uy1cVHFpMPu/eZGqbsTM60k9G0XT4HYB5tWccCFon13upAnT+e/jBIi5qMn2qWjY027bSzr1WUxk5uSKE5SkT5av2VH1Zs25YtB6QkpCj/w7W+6p8hU9nI3LaLz6YAJmC8+04iZ1kxQjph6ZcVhd8LRPlSEPgK+ZKg5ZrQ8MDwFG57tZkXsdv6q+yzk8FZFZRjrb4Asfj2RbyT00zXnOxsAwvTLFK/tn3Gy0fy1BOnp6S9+Ku3CM4Mbf9+YvsZKdCYplJ9/ycbWl3or5+Az5191EDGh1SXiN7gTn5TVzRH9yOf5Y1RAqL/WSWQAKftZHAepR7KDYzF2vtD7EqAIsS/nCaJNicw1Os2EWYfw="

before_install:
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
- ./mvnw clean


install: "./mvnw package"

before_cache:
- ./mvnw cobertura:cobertura coveralls:report sonar:sonar

after_success:
#- ./mvnw cobertura:cobertura coveralls:report sonar:sonar
- bash <(curl -s https://codecov.io/bash)
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/cobertura/coverage.xml

# Make new release mvn -P release-to-oss clean deploy -DupdateReleaseInfo=true -DaltDeploymentRepository=oss::default::https://oss.sonatype.org/service/local/staging/deploy/maven2
